// <auto-generated />
namespace StoreApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddeddboUnit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddeddboUnit));
        
        string IMigrationMetadata.Id
        {
            get { return "201912190944472_Added dbo.Unit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
