// <auto-generated />
namespace StoreApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ChangeinttodecimalindboOrdersandDateTimenullindboDetailsOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeinttodecimalindboOrdersandDateTimenullindboDetailsOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201912221656022_Change int to decimal in dbo.Orders and DateTime null in dbo.DetailsOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
